language: c
matrix:
  include:
    - name: linux-xenial-gcc-win-all
      os: linux
      env: HINTS=linux.2020 LUA_VERSION=5.4.3
      compiler: gcc
      addons:
        apt:
          packages:
            - libx11-dev
            - libxaw7-dev
            - xfonts-utils
            - qtbase5-dev
            - qtmultimedia5-dev
            - qtbase5-dev-tools
      script:
        - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
        - make fetch-lua LUA_VERSION=$LUA_VERSION
        - test -d "lib/lua-$LUA_VERSION/src" || exit 0
        - make LUA_VERSION=$LUA_VERSION WANT_WIN_ALL=1 QT_SELECT=5 MOC=moc install
    - name: linux-bionic-gcc-win-all
      os: linux
      env: HINTS=linux.2020 LUA_VERSION=5.4.3
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - libx11-dev
            - libxaw7-dev
            - xfonts-utils
            - qtbase5-dev
            - qtmultimedia5-dev
            - qtbase5-dev-tools
      script:
        - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
        - make fetch-lua LUA_VERSION=$LUA_VERSION
        - test -d "lib/lua-$LUA_VERSION/src" || exit 0
        - make LUA_VERSION=$LUA_VERSION WANT_WIN_ALL=1 QT_SELECT=5 MOC=moc install
    - name: linux-focal-clang-win-all
      os: linux
      env: HINTS=linux.2020 LUA_VERSION=5.4.3
      dist: focal
      compiler: clang
      addons:
        apt:
          packages:
            - xfonts-utils
            - libx11-dev
            - libxaw7-dev
            - qtbase5-dev
            - qtmultimedia5-dev
            - qtbase5-dev-tools
      script:
        - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
        - make fetch-lua LUA_VERSION=$LUA_VERSION
        - test -d "lib/lua-$LUA_VERSION/src" || exit 0
        - make LUA_VERSION=$LUA_VERSION WANT_WIN_ALL=1 QT_SELECT=5 MOC=moc install
    - name: linux-xenial-gcc-nocommon
      os: linux
      env: HINTS=linux.2020 LUA_VERSION=5.4.3
      dist: xenial
      compiler: gcc
      script:
        - echo "CFLAGS+=-fno-common" >>sys/unix/hints/$HINTS
        - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
        - make fetch-lua LUA_VERSION=$LUA_VERSION
        - test -d "lib/lua-$LUA_VERSION/src" || exit 0
        - make install
    - name: linux-focal-gcc9-win-all
      os: linux
      env: HINTS=linux.2020 LUA_VERSION=5.4.3
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            - gcc-9
            - g++-9
            - libx11-dev
            - libxaw7-dev
            - xfonts-utils
            - qtbase5-dev
            - qtmultimedia5-dev
            - qtbase5-dev-tools
      script:
        - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
        - make fetch-lua LUA_VERSION=$LUA_VERSION
        - test -d "lib/lua-$LUA_VERSION/src" || exit 0
        - make LUA_VERSION=$LUA_VERSION WANT_WIN_ALL=1 QT_SELECT=5 MOC=moc install
    - name: linux-xenial-gcc-minimal
      os: linux
      env: HINTS=linux-minimal LUA_VERSION=5.4.3
      compiler: gcc
      script: |
              cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
              sed -i '/^#define CLIPPING/d'       include/config.h
              sed -i '/^#define COMPRESS/d'       include/config.h
              #sed -i '/^#define DOAGAIN/d'        include/config.h
              sed -i '/^#define DUMPLOG/d'        include/config.h
              #sed -i '/^#define GDBPATH/d'        include/config.h
              #sed -i '/^#define GREPPATH/d'       include/config.h
              sed -i '/^#define INSURANCE/d'      include/config.h
              sed -i '/^#define LOGFILE/d'        include/config.h
              sed -i '/^#define NEWS/d'           include/config.h
              sed -i '/^#define PANICLOG/d'       include/config.h
              #sed -i '/^#define STATUS_HILITES/d' include/config.h
              sed -i '/^#define SYSCF/d'          include/config.h
              sed -i '/^#define USER_SOUNDS/d'    include/config.h
              sed -i '/^#define XLOGFILE/d'       include/config.h
              sed -i '/^#define MAIL/d'           include/unixconf.h
              sed -i '/^#define SHELL/d'          include/unixconf.h
              sed -i '/^#define SUSPEND/d'        include/unixconf.h
              sed -i 's/^#define TEXTCOLOR//'     include/unixconf.h
              make fetch-lua LUA_VERSION=$LUA_VERSION
              test -d "lib/lua-$LUA_VERSION/src" || exit 0
              make LUA_VERSION=$LUA_VERSION WANT_WIN_ALL=1 install
              cat dat/options
    - name: windows-visualstudio
      os: windows
      language: shell
      script:
        - ./win/win32/vs/travisci.sh
#    - name: windows-mingw
#      os: windows
#     install: choco install mingw
#      script:
#        - export ADD_CURSES=Y
#        - export PDCURSES_TOP=../lib/pdcurses
#        - export LUA_VERSION=5.4.0
#        - sh sys/winnt/travis-gcc.sh
#        - test -d "lib/lua-$LUA_VERSION/src" || exit 0
#        - test -d "lib/pdcurses" || exit 0
#        - cd src
#        - cp ../sys/winnt/Makefile.gcc ./Makefile
#        - mingw32-make LUA_VERSION=$LUA_VERSION install
#    - name: msdos-linux-focal-djgpp-crosscompile
#      os: linux
#      env: HINTS=linux.2020 LUA_VERSION=5.4.0
#      dist: focal
#      compiler: gcc
#      script:
#        - export
#        - export GCCVER=gcc550
#        - export GCCVER=gcc1010
#        - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
#        - make fetch-lua
#        - test -d "lib/lua-$LUA_VERSION/src" || exit 0
#        - sh sys/msdos/fetch-cross-compiler.sh
#        - make LUA_VERSION=$LUA_VERSION WANT_WIN_TTY=1 WANT_WIN_CURSES=1 CROSS_TO_MSDOS=1 all
#        - make LUA_VERSION=$LUA_VERSION WANT_WIN_TTY=1 WANT_WIN_CURSES=1 CROSS_TO_MSDOS=1 package
  exclude:
#    - os: osx
#      osx_image: xcode10.3
#      env: DESCR=osx-xcode10.3-x11 HINTS=macosx10.14 WANT_WIN_CURSES=1 WANT_WIN_X11=1 USE_XPM=1
#      compiler: clang
#      script: "cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../ && make install"
    - os: osx
      osx_image: xcode10.2
      env: HINTS=macosx10.14
      compiler: clang
      script: "cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../ && make install"
sudo: false
deploy:
  provider: releases
  api_key:
    secure: b/g11ewW6d6oeulqVXmrdeaTP1PBh60EDZvB6b2pyQxT/MTfL0hrVuuXutdSUKWhams2bxeCfzUCdmC3siqSlyXLDpUHhPRnW+Y8TNVApB6Dymg+nbi/+5d/v/wUSYfBJDm6o7dUMJHS5g8xO8RKFhLXu9fbmg0OrcOc42xaa+OHAqJZF+a2oZTnf/olv57PDOsBXOS6q7A5160IpH4wFkoT/4m6xdqGRNjePWQIrzzH3Jsnqf4o9pbpbCFOKHW9ekWqc+y6QBBOxQO+grhSwbAHCs8afCTPJEQ7TMSBMN6XyvyLGYepv/1BPxd5onm6aKcCaKgDyqHrNObjEyy1tH/a9WL4LegoOFSK7RJuBPUyCjYyPQ2o9mY0/ctrh6ta/JL5zVhNmdEC/jZvU5NyBSMkZy/c4as9Lq7CSuvhsjLCic/lR8Kfr9pae6EpG8oNfrMUcUMH+dulF4eRRyIzV+9beRDhIFjXue6UIRFlaBAw0XOlD3poW6lgurPzyC/v4Kji+tcds65uoq3jVTB/8wQckqOANOziOLCvI1OrvwnHVYt7G3Oa1NSaMwN3yF0fIsWqq1hDwz8M4c4wzrLJauCYdM0a85EHHjSo2nChLDEMiYdUNSY/r5++r8QMj0GCYwB9Xx/5ew6BTfLgmz2EN1XUg+7xwAn0n0LGYR5qcBA=
  file_glob: true
  file:
    - "$TRAVIS_TAG.x86.zip"
  skip_cleanup: true
  on:
    tags: true
  prerelease: true
  name: "Splice-R 1.1.0"
  body: "This is an auto generated release build of Splice-R 1.1.0"